const data = [
  { id: 901, word: 'distinct', choices: ['予備の', '原子力の', '実際の', 'まったく異なった'], correct: 3, sentence: 'The twin brothers have quite distinct tastes.', jp: 'その双子の兄弟はまったく別の好みを持っている。' },
  { id: 902, word: 'overall', choices: ['ほとんど', '基本的には', '全体的に', '定期的に'], correct: 2, sentence: 'Overall, the result of the experiment was satisfactory.', jp: '全体的に，その実験の結果は満足のいくものだった。' },
  { id: 903, word: 'phrase', choices: ['読み書き能力', '言い回し', '多量', 'クモの巣'], correct: 1, sentence: 'Let\'s try using some simple words and phrases in English.', jp: '英語でいくつか簡単な語句を使ってみましょう。' },
  { id: 904, word: 'channel', choices: ['家庭教師', '製造業者', 'チャンネル', '食料雑貨店'], correct: 2, sentence: 'Our television picks up only four channels.', jp: 'うちのテレビは4つのチャンネルしか映らない。' },
  { id: 905, word: 'skip', choices: ['沈む', '省く', '手術する', '集中する'], correct: 1, sentence: 'I tend to skip breakfast even though it is not a good idea.', jp: '私は朝食を抜きがちだ。よくないことではあるのだが。' },
  { id: 906, word: 'ahead', choices: ['前方に', '落ち着いて', '声に出して', '全体的に'], correct: 0, sentence: 'You should look straight ahead when you drive a car.', jp: '車を運転する時はまっすぐ前を見るべきだ。' },
  { id: 907, word: 'aloud', choices: ['ほとんど', '基本的には', '前方に', '声に出して'], correct: 3, sentence: 'I like to sing aloud in the shower.', jp: '私はシャワーを浴びながら声を出して歌うのが好きだ。' },
  { id: 908, word: 'fundamental', choices: ['無作為の', '基本的な', 'ストレスの多い', '落ち着いた'], correct: 1, sentence: 'The fundamental difference between them is their size.', jp: '両者の根本的な違いはその大きさだ。' },
  { id: 909, word: 'prime', choices: ['知的な', '典型的な', 'かなりの', '太りすぎの'], correct: 1, sentence: 'It is a prime example of a Japanese-style shrine.', jp: 'それは日本式の神社の典型的な例である。' },
  { id: 910, word: 'radical', choices: ['主要な', '大きい', 'まったく異なった', '急激な'], correct: 3, sentence: 'Radical political changes are now taking place in the country.', jp: 'その国では現在急激な政治変化が起きつつある。' },
  { id: 911, word: 'virtually', choices: ['落ち着いて', '前方に', '全体的に', 'ほとんど'], correct: 3, sentence: 'It is virtually impossible to tell the two sisters apart.', jp: '２人の姉妹を見分けるのはほとんど不可能だ。' },
  { id: 912, word: 'mechanics', choices: ['機械工学', '遅延', '論文', '礼拝'], correct: 0, sentence: 'I want to study mechanics at university in order to become an engineer.', jp: 'エンジニアになるために大学で機械工学を学びたい。' },
  { id: 913, word: 'mechanism', choices: ['骨', '散らかった状態', '装置', '講義'], correct: 2, sentence: 'After taking the mechanism apart, he found it easy to put it back together.', jp: '装置を分解した後，彼は簡単に元に戻せることに気づいた。' },
  { id: 914, word: 'web', choices: ['読み書き能力', 'クモの巣', '仕組み', '機械工学'], correct: 1, sentence: 'In autumn you can see spider webs on the trees in the morning.', jp: '秋になると，朝，木々にクモの巣を見ることができる。' },
  { id: 915, word: 'operate', choices: ['じっと見る', '省く', '手術する', 'ちらりと見る'], correct: 2, sentence: 'Dr. Smith operated on my father for lung cancer.', jp: 'スミス先生が私の父の肺がんの手術をした。' },
  { id: 916, word: 'basically', choices: ['基本的には', '定期的に', '全体的に', '落ち着いて'], correct: 0, sentence: 'Basically, we do not have enough money to travel abroad.', jp: '基本的に私たちには海外旅行に行くほどのお金はありません。' },
  { id: 917, word: 'intellectual', choices: ['典型的な', '根本的な', '知的な', '基本的な'], correct: 2, sentence: 'He enjoys intellectual discussions about politics and society.', jp: '彼は政治や社会についての知的な議論を楽しんでいる。' },
  { id: 918, word: 'literacy', choices: ['物理学', '奨学金', '規則', '読み書き能力'], correct: 3, sentence: 'The government aims to increase the literacy rate.', jp: '政府は識字率の向上を目指している。' },
  { id: 919, word: 'ton', choices: ['多量', '目的', '意図', '言い回し'], correct: 0, sentence: 'It is estimated that there are tons of plastic waste in the ocean.', jp: '海にはたくさんのプラスチックごみがあると推定されている。' },
  { id: 920, word: 'outweigh', choices: ['より重要である', '延期する', '侮辱する', 'あいさつする'], correct: 0, sentence: 'The advantages far outweigh any disadvantages.', jp: 'メリットがどんなデメリットをもはるかに上回る。' },
  { id: 921, word: 'obesity', choices: ['食料雑貨店', '肥満', '説明書', '苦情'], correct: 1, sentence: 'Obesity rates are rising in most countries.', jp: '肥満率はほとんどの国で上昇している。' },
  { id: 922, word: 'overweight', choices: ['太りすぎの', '利益になる', '予備の', '知的な'], correct: 0, sentence: 'He\'s a little overweight.', jp: '彼は少し太りすぎだ。' },
  { id: 923, word: 'tongue', choices: ['遅延', '論文', '目撃者', '舌'], correct: 3, sentence: 'His mother tongue is English, but he speaks Spanish at work.', jp: '彼の母語は英語だが，職場ではスペイン語を話す。' },
  { id: 924, word: 'chew', choices: ['かむ', '祝う', '注射する', 'くみ上げる'], correct: 0, sentence: 'Chew your food well before you swallow it.', jp: '食べ物はよく噛んでから飲み込みましょう。' },
  { id: 925, word: 'considerable', choices: ['ストレスの多い', '落ち着いた', 'かなりの', '大きい'], correct: 2, sentence: 'We spent a considerable amount of time preparing for the festival.', jp: 'その祭の準備にかなりの時間を費やした。' },
  { id: 926, word: 'profitable', choices: ['原子力の', 'かなりの', '太りすぎの', '利益になる'], correct: 3, sentence: 'After three years, the company finally became profitable.', jp: '3年後，その会社はついに利益を出せるようになった。' },
  { id: 927, word: 'concentrate', choices: ['集中する', '現れる', 'おぼれ死ぬ', '滑る'], correct: 0, sentence: 'I was concentrating on my book and didn\'t hear the doorbell ring.', jp: '本に集中していて，ドアベルが鳴るのが聞こえなかった。' },
  { id: 928, word: 'flavor', choices: ['風味', '放射線', '化石', '要素'], correct: 0, sentence: 'What flavor would you like?', jp: 'どんな味がよいですか。' },
  { id: 929, word: 'distract', choices: ['注意をそらす', '焼く', '配達する', '炒る'], correct: 0, sentence: 'My younger brother always distracts me when I am trying to study.', jp: '私が勉強しようとすると，弟がいつも私の気をそらしてくる。' },
  { id: 930, word: 'extract', choices: ['取り出す', '押収する', 'つかむ', '把握する'], correct: 0, sentence: 'Maple syrup is extracted from the maple tree.', jp: 'メープルシロップはカエデの木から抽出される。' },
  { id: 931, word: 'spare', choices: ['実際の', '主要な', '無作為の', '予備の'], correct: 3, sentence: 'Could you spare me a few minutes?', jp: '私に数分割いてくださいますか。' },
  { id: 932, word: 'drown', choices: ['おぼれ死ぬ', '繁栄する', '省く', '沈む'], correct: 0, sentence: 'He rescued a child drowning in the lake.', jp: '彼は湖で溺れて死にかけている子供を助けた。' },
  { id: 933, word: 'bake', choices: ['焼く', '分配する', '強調する', '説明する'], correct: 0, sentence: 'I baked a cake for my mother\'s birthday.', jp: '母の誕生日にケーキを焼きました。' },
  { id: 934, word: 'roast', choices: ['直面する', '果たす', '受け入れる', '炒る'], correct: 3, sentence: 'He often roasts coffee beans himself.', jp: '彼はよく自分でコーヒー豆を炒る。' },
  { id: 935, word: 'deliver', choices: ['祝う', '侮辱する', 'あいさつする', '配達する'], correct: 3, sentence: 'The principal delivers the same speech at the entrance ceremony every year.', jp: '校長は毎年入学式で同じスピーチをする。' },
  { id: 936, word: 'distribute', choices: ['注意をそらす', 'より重要である', '分配する', 'かむ'], correct: 2, sentence: 'I stood on the street corner and distributed leaflets to people walking past.', jp: '私は街角に立って，通り過ぎる人々にビラを配った。' },
  { id: 937, word: 'instruction', choices: ['指示', '肥満', '風味', '舌'], correct: 0, sentence: 'The teacher gave clear instructions on how to apply for the summer seminar.', jp: '先生は夏期セミナーの申し込み方法を明確に指示した。' },
  { id: 938, word: 'illustrate', choices: ['満足させる', '延期する', '備え付ける', '説明する'], correct: 3, sentence: 'There are many pictures to illustrate the story and help you understand it.', jp: '物語を説明し，理解するのに役立つ絵がたくさんある。' },
  { id: 939, word: 'tutor', choices: ['構成要素', '目撃者', '家庭教師', '格子'], correct: 2, sentence: 'I have an English tutor twice a week.', jp: '私は週に2回英語の家庭教師をつけています。' },
  { id: 940, word: 'emphasize', choices: ['強調する', '取り出す', '焼く', '炒る'], correct: 0, sentence: 'He emphasized the point by banging his hand on the table.', jp: '彼はテーブルに手を叩きつけてポイントを強調した。' },
  { id: 941, word: 'manufacturer', choices: ['散らかった状態', '骨', '製造業者', '目的'], correct: 2, sentence: 'We are the leading manufacturer of computer chips in Japan.', jp: '私たちは日本におけるコンピューターチップのトップメーカーです。' },
  { id: 942, word: 'grocery', choices: ['クモの巣', '読み書き能力', '仕組み', '食料雑貨店'], correct: 3, sentence: 'I tend to buy my daily groceries from the same supermarket every day.', jp: '私は毎日同じスーパーで日々の食料品を買うことが多い。' },
  { id: 943, word: 'manual', choices: ['肉体', '指示', '製造業者', '家庭教師'], correct: 0, sentence: 'Over the summer I worked as a manual laborer on a building site.', jp: '夏の間，私は建築現場で肉体労働者として働いた。' },
  { id: 944, word: 'slip', choices: ['滑る', '手術する', 'じっと見る', '集中する'], correct: 0, sentence: 'I\'m not good at skating, so I often slip on the ice.', jp: '私はスケートが得意ではないので，よく氷の上で滑って転んでしまう。' },
  { id: 945, word: 'complaint', choices: ['目撃者', '要素', '構成要素', '苦情'], correct: 3, sentence: 'I have a complaint about the food at your restaurant.', jp: 'おたくのレストランの料理に不満があるんです。' },
  { id: 946, word: 'emerge', choices: ['現れる', 'おぼれ死ぬ', '沈む', 'ちらりと見る'], correct: 0, sentence: 'He has emerged as the leading candidate for the position of Prime Minister.', jp: '彼が首相の最有力候補として浮上してきた。' },
  { id: 947, word: 'emergency', choices: ['意図', '緊急事態', 'チャンネル', '言い回し'], correct: 1, sentence: 'He always stays calm in an emergency.', jp: '彼は非常時にはいつも落ち着いている。' },
  { id: 948, word: 'urge', choices: ['分配する', '駆り立てる', '配達する', '説明する'], correct: 1, sentence: 'The government urged people to save energy.', jp: '政府は人々にエネルギーを節約するように促した。' },
  { id: 949, word: 'bond', choices: ['食料雑貨店', '説明書', 'きずな', '苦情'], correct: 2, sentence: 'The two friends formed a close bond in elementary school.', jp: '2人の友人は小学校時代に親密なきずなを結んだ。' },
  { id: 950, word: 'journal', choices: ['放射線', '雑誌', '障害物', '格子'], correct: 1, sentence: 'I enjoy reading journals on nature.', jp: '私は自然に関する雑誌を読むのが好きです。' },
  { id: 951, word: 'preference', choices: ['論文', '礼拝', '好み', '遅延'], correct: 2, sentence: 'His preference for sweet food is not healthy.', jp: '彼の甘い食べ物への好みは健康的ではない。' },
  { id: 952, word: 'hydrogen', choices: ['散らかった状態', '水素', '骨', '講義'], correct: 1, sentence: 'Companies are trying to design a car that can run on hydrogen.', jp: '企業は水素で走る車を設計しようとしている。' },
  { id: 953, word: 'block', choices: ['クモの巣', '仕組み', '区画', '機械工学'], correct: 2, sentence: 'Walk about three blocks along this road, and you will see the library.', jp: 'この道を3ブロックほど歩くと図書館が見える。' },
  { id: 954, word: 'grid', choices: ['格子', '風味', '家庭教師', '指示'], correct: 0, sentence: 'The map has grid lines from north to south and from east to west.', jp: '地図には南北と東西に格子線が引かれている，' },
  { id: 955, word: 'nuclear', choices: ['大きい', '基本的な', 'まったく異なった', '原子力の'], correct: 3, sentence: 'The use of nuclear power has fallen in that country.', jp: 'その国では原子力の利用が減少した。' },
  { id: 956, word: 'radiation', choices: ['構成要素', '要素', '化石', '放射線'], correct: 3, sentence: 'This device can measure the levels of radiation.', jp: 'この装置は放射線レベルを測定することができる。' },
  { id: 957, word: 'fossil', choices: ['物理学', '規則', '奨学金', '化石'], correct: 3, sentence: 'All fossil fuels are made up of carbon compounds.', jp: '化石燃料はすべて炭素化合物でできている。' },
  { id: 958, word: 'element', choices: ['目的', '意図', '要素', '言い回し'], correct: 2, sentence: 'Calcium is a key element of healthy teeth and bones.', jp: 'カルシウムは健康な歯と骨の重要な要素である。' },
  { id: 959, word: 'component', choices: ['多量', '肥満', '読み書き能力', '構成要素'], correct: 3, sentence: 'Music has been a key component of our culture.', jp: '音楽は我々の文化の重要な構成要素であり続けている。' },
  { id: 960, word: 'grasp', choices: ['受け入れる', '押収する', '直面する', '把握する'], correct: 3, sentence: 'Finally, I could begin to grasp the meaning of the lecture.', jp: 'ようやく講義の意味を理解できるようになった。' },
  { id: 961, word: 'grab', choices: ['祝う', 'あいさつする', 'つかむ', '侮辱する'], correct: 2, sentence: 'He quickly grabbed his bag off the table.', jp: '彼はテーブルから素早くバッグを取った。' },
  { id: 962, word: 'seize', choices: ['より重要である', 'かむ', '押収する', '注意をそらす'], correct: 2, sentence: 'Police seized all the illegal documents.', jp: '警察はすべての違法文書を押収した。' },
  { id: 963, word: 'embrace', choices: ['説明する', '受け入れる', '分配する', '強調する'], correct: 1, sentence: 'Some managers find it difficult to embrace any better ideas from their subordinates.', jp: '経営者の中には部下からのよい意見を受け入れるのが難しいと思う人もいる。' },
  { id: 964, word: 'encounter', choices: ['果たす', '受け入れる', '満足させる', '直面する'], correct: 3, sentence: 'We encountered the enemy outside of the town.', jp: '我々は町の外で敵に遭遇した。' },
  { id: 965, word: 'witness', choices: ['舌', '指示', '目撃者', '風味'], correct: 2, sentence: 'The small child witnessed the murder.', jp: '小さな子供が殺人を目撃した。' },
  { id: 966, word: 'actual', choices: ['実際の', '根本的な', '典型的な', 'ストレスの多い'], correct: 0, sentence: 'The actual story is less interesting than in the movie.', jp: '実際の話は映画よりおもしろくない。' },
  { id: 967, word: 'thesis', choices: ['化石', '放射線', '論文', '格子'], correct: 2, sentence: 'I wrote my thesis on how learners remember items of vocabulary.', jp: '私は学習者がどのように語彙の項目を記憶するかについて論文を書いた。' },
  { id: 968, word: 'fulfill', choices: ['侮辱する', '果たす', '延期する', '備え付ける'], correct: 1, sentence: 'The candidate fulfilled all the requirements of the job application.', jp: 'その応募者は求人応募のすべての条件を満たしていた。' },
  { id: 969, word: 'satisfy', choices: ['回復させる', 'くみ上げる', '反映する', '満足させる'], correct: 3, sentence: 'I felt satisfied after my long walk.', jp: '長い散歩の後，私は満足を感じた。' },
  { id: 970, word: 'equip', choices: ['炒る', '焼く', '備え付ける', '配達する'], correct: 2, sentence: 'The car is equipped with air bags for safety.', jp: '車には安全のためエアバッグが装備されている。' },
  { id: 971, word: 'thrive', choices: ['繁栄する', '現れる', '滑る', '集中する'], correct: 0, sentence: 'He has a thriving shop in the new mall.', jp: '彼は新しいモールに繁盛店を持っている。' },
  { id: 972, word: 'delay', choices: ['遅らせる', '好み', '水素', '日誌'], correct: 0, sentence: 'The train was delayed because there was a person on the tracks.', jp: '列車は線路に人がいたため遅れた。' },
  { id: 973, word: 'postpone', choices: ['延期する', 'より重要である', '注意をそらす', 'かむ'], correct: 0, sentence: 'The athletic meeting was postponed till a fine day.', jp: '運動会は晴れの日まで延期された。' },
  { id: 974, word: 'worship', choices: ['関係', '規則', '礼拝', '講義'], correct: 2, sentence: 'Many places of worship are now popular tourist attractions.', jp: '今では多くの礼拝所が人気の観光スポットとなっている。' },
  { id: 975, word: 'scholarship', choices: ['チャンネル', '言い回し', '機械工学', '奨学金'], correct: 3, sentence: 'I won a scholarship to study in the US for two years.', jp: '私はアメリカに2年間留学するための奨学金を得た。' },
  { id: 976, word: 'physics', choices: ['舌', '肥満', '物理学', '風味'], correct: 2, sentence: 'The university has one of the leading physics departments in the country.', jp: 'その大学には国内有数の物理学科がある。' },
  { id: 977, word: 'insult', choices: ['侮辱する', '分配する', '説明する', '取り出す'], correct: 0, sentence: 'He insulted her by calling her a selfish person.', jp: '彼は彼女をわがままな人と呼んで侮辱した。' },
  { id: 978, word: 'regulation', choices: ['放射線', '規則', '障害物', '格子'], correct: 1, sentence: 'Many industries have their own set of regulations.', jp: '多くの業界には一連の独自の規制がある。' },
  { id: 979, word: 'relation', choices: ['遅延', '礼拝', '論文', '関係'], correct: 3, sentence: 'The two countries are now on good relations after a period of distrust.', jp: '両国は不信の時期を経て，今は良好な関係にある。' },
  { id: 980, word: 'lecture', choices: ['目的', '散らかった状態', '骨', '講義'], correct: 3, sentence: 'The professor gave a lecture on the Edo period.', jp: '教授は江戸時代について講義した。' },
  { id: 981, word: 'stare', choices: ['じっと見る', '手術する', '省く', '繁栄する'], correct: 0, sentence: 'The man was staring at me and I felt really uncomfortable.', jp: '男は私をじっと見ており本当に不快だった。' },
  { id: 982, word: 'glance', choices: ['省く', 'ちらりと見る', '沈む', 'じっと見る'], correct: 1, sentence: 'I glanced at the clock to see how much time was left in the exam.', jp: '試験の残り時間を確認するため，時計をちらっと見た。' },
  { id: 983, word: 'loud', choices: ['落ち着いた', '知的な', '太りすぎの', 'うるさい'], correct: 3, sentence: 'When I was young, I listened to loud music all the time.', jp: '若い頃は大音量の音楽をいつも聴いていた。' },
  { id: 984, word: 'regularly', choices: ['前方に', '定期的に', '全体的に', '声に出して'], correct: 1, sentence: 'I regularly visit the dentist.', jp: '私は定期的に歯医者に通っている。' },
  { id: 985, word: 'greet', choices: ['あいさつする', '主張する', '強調する', '把握する'], correct: 0, sentence: 'The manager greeted his new clients very politely.', jp: '店長は新しい客にとても丁寧に挨拶した。' },
  { id: 986, word: 'celebrate', choices: ['受け入れる', '押収する', '祝う', 'つかむ'], correct: 2, sentence: 'My parents are celebrating their 25th wedding anniversary.', jp: '私の両親は結婚25周年を祝っている。' },
  { id: 987, word: 'sink', choices: ['おぼれ死ぬ', '滑る', '沈む', 'ちらりと見る'], correct: 2, sentence: 'The ship silently sank into the sea.', jp: '船は静かに海に沈んだ。' },
  { id: 988, word: 'mess', choices: ['説明書', '食料雑貨店', '散らかった状態', '苦情'], correct: 2, sentence: 'After the children\'s party, the parents helped clean up the mess.', jp: '子供たちのパーティーのあと，親たちは散らかしたものを片付けるのを手伝った。' },
  { id: 989, word: 'calmly', choices: ['定期的に', '基本的には', '落ち着いて', 'ほとんど'], correct: 2, sentence: 'He walked calmly into the interview.', jp: '彼は落ち着いてインタビューに入っていった。' },
  { id: 990, word: 'calm', choices: ['落ち着いた', '利益になる', '予備の', 'かなりの'], correct: 0, sentence: 'He has a calm voice that makes everybody feel relaxed.', jp: '彼は誰もがリラックスできる落ち着いた声の持ち主だ。' },
  { id: 991, word: 'inject', choices: ['くみ上げる', 'あいさつする', '注射する', '祝う'], correct: 2, sentence: 'The doctor injected the patient with some medicine to make her sleep.', jp: '医師は患者を眠らせるために薬を注射した。' },
  { id: 992, word: 'pump', choices: ['焼く', '注意をそらす', 'くみ上げる', '取り出す'], correct: 2, sentence: 'At that time, people around here pumped water from the well.', jp: '当時，この辺りの人々はこの井戸から水をくみ上げていた。' },
  { id: 993, word: 'bone', choices: ['指示', '家庭教師', '骨', '風味'], correct: 2, sentence: 'I once fell from a tree and broke two bones in my arm.', jp: '私は昔，木から落ちて腕の骨を2本折った。' },
  { id: 994, word: 'aim', choices: ['緊急事態', '目的', '日誌', 'きずな'], correct: 1, sentence: 'The company aims to expand its business by 25%.', jp: '会社は25％の事業拡大を目指している。' },
  { id: 995, word: 'stressful', choices: ['大きい', '原子力の', 'ストレスの多い', '実際の'], correct: 2, sentence: 'Working for that company is really stressful.', jp: 'その会社で働くのは本当にストレスが多い。' },
  { id: 996, word: 'restore', choices: ['分配する', '炒る', '配達する', '回復させる'], correct: 3, sentence: 'It took a couple of days to restore power to the town.', jp: 'その町の電力を復旧させるのに2，3日かかった。' },
  { id: 997, word: 'intention', choices: ['骨', '言い回し', '目的', '意図'], correct: 3, sentence: 'My intention is to retire when I am 60 years old.', jp: '私は60歳で引退するつもりだ。' },
  { id: 998, word: 'random', choices: ['落ち着いた', '主要な', '無作為の', 'ストレスの多い'], correct: 2, sentence: 'The most secure passwords consist of a series of random letters.', jp: '最も安全なパスワードは無作為な文字列で構成される。' },
  { id: 999, word: 'reflect', choices: ['反映する', 'より重要である', 'かむ', '回復させる'], correct: 0, sentence: 'His success reflects the fact that he worked so hard.', jp: '彼の成功は彼が一生懸命働いた事実を反映している。' },
  { id: 1000, word: 'chief', choices: ['まったく異なった', '無作為の', '基本的な', '主要な'], correct: 3, sentence: 'He is the chief of our section.', jp: '彼は私たちのセクションの長だ。' },
];